### ISSUE TITLE
git submodule --progress option only works with git >= 2.11

### ISSUE THREAD

**Issue by wgurecky** [wbthomason/packer.nvim#747]
The default git submodule command only works with git >=2.11 (https://stackoverflow.com/questions/32944468/how-to-show-progress-for-submodule-fetching) . 

https://github.com/wbthomason/packer.nvim/blob/851c62c5ecd3b5adc91665feda8f977e104162a5/lua/packer.lua#L39

Consider removing the `--progress` argument to maintain compatibility with git<2.11 .

**Comment by fwip** [comment]
Ah, this must be why all of my updates are failing with errors like:

```
  Errors:
    remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
    HEAD is now at 518e275... Update lockfile.json
    remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
    usage: git submodule [--quiet] add [-b <branch>] [-f|--force] [--name <name>] [--reference <repository>] [--] <repository> [<path>]
       or: git submodule [--quiet] status [--cached] [--recursive] [--] [<path>...]
       or: git submodule [--quiet] init [--] [<path>...]
       or: git submodule [--quiet] deinit [-f|--force] (--all| [--] <path>...)
       or: git submodule [--quiet] update [--init] [--remote] [-N|--no-fetch] [-f|--force] [--checkout|--merge|--rebase] [--reference <repository>] [--recursiv
       or: git submodule [--quiet] summary [--cached|--files] [--summary-limit <n>] [commit] [--] [<path>...]
       or: git submodule [--quiet] foreach [--recursive] <command>
       or: git submodule [--quiet] sync [--recursive] [--] [<path>...]
    518e275
```

With git 2.9.5.
